name: CI

on:
  push:
    branches: ["master", "main" ]
  pull_request:
    branches: ["master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ats-resume-analyzer:${{ github.sha }}